### ISSUE TITLE
Example in Section 5.4.1: hashing the license document

### ISSUE THREAD

**Issue by dauwhe** [readium/readium-lcp-specs#1]
Section 5.4.1 of the [LCP spec](https://readium.github.io/readium-lcp-specification/ ) shows a canonical LCP license document. 

```json
{"encryption":{"content_key":{"algorithm":"http://www.w3.org/2001/04/xmlenc#aes256-cbc","encrypted_value":"/k8RpXqf4E2WEunCp76E8PjhS051NXwAXeTD1ioazYxCRGvHLAck/KQ3cCh5JxDmCK0nRLyAxs1X0aA3z55boQ=="},"profile":"http://readium.org/lcp/basic-profile","user_key":{"algorithm":"http://www.w3.org/2001/04/xmlenc#sha256","key_check":"jJEjUDipHK3OjGt6kFq7dcOLZuicQFUYwQ+TYkAIWKm6Xv6kpHFhF7LOkUK/Owww","text_hint":"Enter your email address"}},"id":"ef15e740-697f-11e3-949a-0800200c9a66","issued":"2013-11-04T01:08:15+01:00","links":[{"rel":"hint","href":"http://www.imaginaryebookretailer.com/lcp/hint","type":"text/html"}],"provider":"http://www.imaginaryebookretailer.com","updated":"2014-02-21T09:44:17+01:00","user":{"id":"d9f298a7-7f34-49e7-8aae-4378ecb1d597"}}
```

and its SHA-256 Hash:

```
ce3fd2220fc26c89ed2190fd27af39c4016b623dd2bd5e5a3562dc0795769c92
```

What's puzzling me is that when I calculate this hash either with an [online service](http://www.xorbin.com/tools/sha256-hash-calculator) or using openssl directly ( `openssl dgst -sha256 license.lcpl`), I get a different value:

```
f033359cf41210e48765382e15e794fa9e376a3df61d87631da96e54905e12ce
```

I'm sure I'm missing something obvious. But I'm running into similar issues when working with the lcp server, where I'm unable to, for example, correctly generate the `key_check` from my passphrase and the license `id`. Are there perhaps assumptions about how the cryptographic functions are used that are not yet documented in the spec?

**Comment by HadrienGardeur** [comment]
There's no undocumented function that I'm aware of.

For the server implementation, @jpbougie or @danielweck can probably provide more details.

**Comment by danielweck** [comment]
Note the existence of this handy LCP verifier tool:
https://github.com/edrlab/lcp-testing-tools/tree/master/SignatureVerifier_Java
I use it regularly to check LCPL certificates and signatures.

**Comment by danielweck** [comment]
Doesn't the LCP Go server implementation generates a license based on the hashed passphrase (user key) passed in the HTTP request parameter (JSON body)?

**Comment by danielweck** [comment]
If the LCP signature examples in the specification are wrong, then they indeed need fixing. Thanks for bringing this up! :)
