### ISSUE TITLE
LSD specs, event values

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-specs#13]
In section 2.7 Events, event type values are currently defined as "Link relations as defined in section 2. Status Document or in 3. Interactions" which is wrong as section 2. only defines 'license' as a link relation.

We could define it as "Status values as defined in section 2. Status Document or Link relations as defined in section 3. Interactions". This would still leave an issue, as status values are 'ready', 'active', 'revoked', 'returned', 'cancelled', 'expired' whilst interaction values are 'register', 'renew' and 'return'.

But 'register' and 'active' mean the same in practice, as 'returned' and 'return'. The only interesting interaction value is 'renew'. 

My proposal is therefore to define a registry document instead, with all the values of a status (e.g. returned') plus 'renewed' as an additional value.

Also, the only event sample, in 1.3 shows an undefined event type ('activate'). Should be replaced by 'active'.

**Comment by llemeurfr** [comment]
Alternatively, I'd be ok with active words, i.e. 
'register', 'renew', 'return', 'revoke', 'cancel'.

**Comment by llemeurfr** [comment]
The new draft of LSD specs explicitly lists the latter proposal. I'll modify the EDRLab LCP server codebase now. The DeMarque codebase is still using these values.

**Comment by HadrienGardeur** [comment]
I like this update, it covers the main events that can be triggered either by a client or the issuer.

**Comment by llemeurfr** [comment]
ok, so I update the LSD spec today, no need for a new version, it's only a precision.
