### ISSUE TITLE
LSD specs, erroneous mime-type for links to license in samples 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-specs#15]
The proper mimi-type of a license, as defined in the LCP spec, is application/vnd.readium.lcp.license-1.0+json.
... with a hyphen.

In the LSD spec, there as several occurences of 
application/vnd.readium.lcp.license.1.0+json
... with a dot. 

These must be corrected.

**Comment by HadrienGardeur** [comment]
I'd like to re-open that issue since I'd like to align the media type for LCP License and the Status Document.

Currently for the Status Document, we have the following media type: `application/vnd.readium.license.status.v1.0+json`

Can we decide on dot versus hyphen, and whether we need the "v" and align both specs accordingly?

cc @jpbougie

**Comment by llemeurfr** [comment]
It's true that the 2 mime-types are not aligned. As there a only two LCP server implementations ready for certification today, EDRLab and DeMarque, if DeMarque is willing to make the change "now" on its implementation, EDRLab can do the same and the alignment is possible. But time is really short...

**Comment by HadrienGardeur** [comment]
We'll also need to register both MIME types at IANA, by the way. Will EDRLab handle that?

**Comment by llemeurfr** [comment]
This is another issue. Yes, EDRLAb can handle that.

**Comment by llemeurfr** [comment]
If an alignment of syntax is decided, we also have to keep in mind that the "-1.0" pattern is used in the profile identifier =  "http://readium.org/lcp/profile-1.0".

**Comment by jpbougie** [comment]
We can change whenever required. I will defer to you as to the proper syntax, I have little experience with the best practices

**Comment by HadrienGardeur** [comment]
There's always a risk in updated these media types, but I still believe it's worth doing.

IMO the URI for the profile is a different (and less important) issue, but sure, we could align it as well.

**Comment by llemeurfr** [comment]
I've checked on the iOS codebase, the mime-type is not used. I don't like to modify such a part of a spec (which may break implementations) but it's right that IANA declaration will be cleaner with an aligned syntax. 

go for application/vnd.readium.lcp.license.v1.0+json.

**Comment by danielweck** [comment]
Fixed in the TypeScript / NodeJS implementation:
https://github.com/edrlab/r2-shared-js/commit/29d07b39bdfe846cfedaf6f32a1c0357443f1775

**Comment by danielweck** [comment]
I checked https://github.com/readium/readium-lcp-client/tree/develop => no change needed.

**Comment by danielweck** [comment]
I checked https://github.com/readium/SDKLauncher-Android/tree/feature/lcp => no change needed.

**Comment by danielweck** [comment]
I checked https://github.com/readium/SDKLauncher-iOS/tree/feature/lcp => no change needed.

**Comment by danielweck** [comment]
I checked https://github.com/readium/SDKLauncher-OSX/tree/feature/lcp => no change needed.

**Comment by danielweck** [comment]
https://github.com/readium/readium-sdk/tree/develop is LCP-agnostic, but I checked anyway => no change needed.

**Comment by danielweck** [comment]
I checked `r2-lcp-client` => no change needed.

**Comment by danielweck** [comment]
TODO (?): check Go, Swift, Kotlin, Java source trees?

**Comment by llemeurfr** [comment]
Go is done (server), Swift also. Kotlin will be by Aferdita. Java: nothing on LCP.

**Comment by llemeurfr** [comment]
fixed by 4ff616ee066975abe46d5d428345f5f77011ce79

**Comment by llemeurfr** [comment]
and also fixed by 9de9e44abba3df572f5a4d10be1a5f209fe23995
